[build]
  command = "bun install && bun run build-storybook -- --output-dir storybook-static && mv storybook-static public/storybook && bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"